#!/bin/bash
FILE=$1                                                                 
MCU="$(head -2 $1 | tail -1)"
FILE=${FILE%%.*}
mkdir -p COMPILED
avr-gcc -mmcu=$MCU $1 -o COMPILED/$FILE.o
avr-objcopy -j .text -j .data -O ihex COMPILED/$FILE.o COMPILED/$FILE.hex
sudo dfu-programmer $MCU erase
sudo dfu-programmer $MCU flash COMPILED/$FILE.hex
sudo dfu-programmer $MCU reset
SIZE=$(stat --printf="%s" COMPILED/$FILE.hex)
echo ""
echo $FILE.hex "is "$SIZE" bytes."
